apiVersion: 1

datasources:
  - name: prometheus-gzip
    uid: prometheus-gzip
    type: prometheus
    access: proxy
    url: http://prometheus-gzip:9091
    isDefault: false
    orgId: 1
    version: 1
    editable: true
    jsonData:
      httpMethod: GET

  - name: prometheus-direct
    uid: prometheus-direct
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    orgId: 1
    version: 1
    editable: true
    jsonData:
      httpMethod: GET

  - name: prometheus-search-api
    uid: prometheus-search-api
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    orgId: 1
    version: 1
    editable: true
    jsonData:
      httpMethod: GET
      enableSearchApi: true
