apiVersion: 1

datasources:
  - name: prometheus-search-api
    uid: prometheus-search-api
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    orgId: 1
    version: 1
    editable: true
    jsonData:
      httpMethod: GET
      enableSearchApi: true
