services:
  prometheus:
    image: prom/prometheus:v3.14.0@sha256:5ce7540c3c00ef4ab0c9d2c995c6a5b9c421f44b4a115d97a2c7af3b1c21cbb0
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --enable-feature=search-api,promql-extended-range-selectors
      - --web.listen-address=0.0.0.0:9090
      - --storage.tsdb.path=/prometheus
