FROM golang:1.27.1@sha256:162be5298a40ed317005c8339c6de4d10d3eef336d66dc8e9259b03ab9d3a6d2 AS builder

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY main.go ./
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/utf8 .

FROM scratch
COPY --from=builder /out/utf8 /utf8
EXPOSE 9112
ENTRYPOINT ["/utf8"]
