name: Plugins - CD
run-name: Deploy ${{ inputs.branch }} to ${{ inputs.environment }} by @${{ github.actor }}
permissions:
  attestations: write
  contents: write
  pull-requests: read
  id-token: write

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to publish from. Can be used to deploy PRs to dev
        default: main
      environment:
        description: Environment to publish to. Selecting "ops" publishes to dev as well (if not already done); "prod" publishes to all environments.
        required: true
        type: choice
        options:
          - 'dev'
      scope:
        description: Cloud will publish scoped only to Grafana Cloud, On Prem will publish with Universal scope. Please use Cloud unless emergency fix needed for On Prem customer.
        required: true
        type: choice
        default: 'cloud (recommended)'
        options:
          - 'cloud (recommended)'
          - 'on-prem (for emergencies fix to On Prem customers)'
      docs-only:
        description: Only publish docs, do not publish the plugin
        default: false
        type: boolean

jobs:
  cd:
    name: CD
    uses: grafana/plugin-ci-workflows/.github/workflows/cd.yml@ci-cd-workflows/v7.2.0
    with:
      branch: ${{ github.event.inputs.branch }}
      environment: ${{ github.event.inputs.environment }}
      docs-only: ${{ fromJSON(github.event.inputs.docs-only) }}
      run-playwright: false
      github-draft-release: false
